name: harmony_fire
description: Harmony Firebase and Social Login Mechanism.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0

publish_to: https://unpub.cloud.6thsolution.tech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  harmony_log:
    hosted:
      name: harmony_log
      url: https://unpub.cloud.6thsolution.tech
    version: ^1.0.0
  meta: any
  dio: ^4.0.0
  shared_preferences: ^2.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^3.0.0
  # We can't publish our app without this dependency.
  # Since we should add all the dependencies that we imported in our code in to this section
  firebase_auth_platform_interface: ^6.1.0
  google_sign_in: ^5.0.0
  flutter_facebook_auth: ^3.0.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  mocktail: any
